# permissions for end users to view projectroletemplatebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectroletemplatebinding-viewer-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings/status
  verbs:
  - get
