# permissions for end users to edit projectnamespacemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectnamespacemapping-editor-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projectnamespacemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectnamespacemappings/status
  verbs:
  - get
