# permissions for end users to view projectnamespacemappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectnamespacemapping-viewer-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projectnamespacemappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectnamespacemappings/status
  verbs:
  - get
