
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projectnamespacemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectnamespacemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projectroletemplatebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.cattle.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
